# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family      Iosevka Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 12.0

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

disable_ligatures cursor

# Old pastel theme stuff
# cursor #383a42
# cursor_text_color background
# foreground #383a42
# background #fafafa
# selection_foreground #383a42
# selection_background #e1d4de
# color0 #1b2229
# color8 #1c1f24
#: black
# color1 #ec3b82
# color9 #f0629b
#: red
# color2  #68af9c
# color10 #86bfb0
#: green
# color3  #ff9933
# color11 #ffad5c
#: yellow
# color4  #557ebd
# color12 #7798ca
#: blue
# color5  #e4a3db
# color13 #e9b5e2
#: magenta
# color6  #6e64c2
# color14 #8b83ce
#: cyan
# color7  #fafafa
# color15 #ffffff
#: white

cursor_shape beam

scrollback_lines 20000


kitty_mod hyper

map ctrl+g kitten hints --type=path --program=@ --hints-text-color=red
map ctrl+shift+g kitten hints --type=url --program=vivaldi --hints-text-color=red

#: Preserve cwd when opening windows/tabs
map kitty_mod+enter new_window_with_cwd
map kitty_mod+n new_os_window_with_cwd
map kitty_mod+t new_tab_with_cwd

#: Colemak Keyswaps
#: Swap b and h, p and e, and f and i
# map ctrl+a send_text all \x01
# default already

# map ctrl+p send_text all \x05
map ctrl+p send_text all \e[F
# ctrl-p to go to end of line (\x05 is normally ctrl-e. \e[F is end key I think)

map ctrl+e send_text all \x10
# ctrl-e to go up in history (\x10 is normally ctrl-p)

# NOTE disabling the following so it doesn't shadow ctrl+b in helix editor
# map ctrl+b send_text all \x08
# ctrl-b to delete backward one character

map ctrl+h send_text all \x02
# ctrl-h go left one character

# NOTE disabling the following so it doesn't shadow ctrl+i in helix editor
#map ctrl+i send_text all \x06
# ctrl-i go right one character

map alt+h send_text all \x1bb
# alt-h moves back one word

map alt+i send_text all \x1bf
# alt-i moves forward one word

map ctrl+shift+c copy_to_clipboard
# Shift-Control-c should copy to clipboard. I'd use Control-c, but that's already in use and I don't want to change it.

# Control-x would cut, but there's not really a way for me to do that, and it would only work with mouse selection anyway.

map ctrl+v paste_from_clipboard
# Control-v should paste

map ctrl+shift+v paste_from_selection
# Control-Shift-v should paste from the primary selection


allow_remote_control yes
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Ayu
include current-theme.conf
# END_KITTY_THEME
