#!/bin/bash
# From anachron/i3blocks; modified by taylor-gl

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
toggle_loopback.sh > /dev/null 2>&1
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Capture 5%+
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Capture 5%-
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  amixer -q sset Capture toggle
fi

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $4}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "${volume}%"
  echo "${volume}%"
  echo ""
else
  echo "off"
  echo "off"
  echo ""
fi
