#!/usr/bin/env bash
#
# Render every scheme through every template into theme/out/<variant>/.
#
# Output is committed so a fresh checkout is already themed and nothing has to
# be generated at login. Run this after editing anything under schemes/ or
# templates/, then `switch-to-dark-theme.sh` (or -light) to apply.

set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

render() { python3 ./render.py "$1" "$2"; }

for scheme in schemes/*.yaml; do
    slug=$(basename "$scheme" .yaml)          # burning-sun-dark
    variant=${slug##*-}                       # dark | paper
    out="out/$variant"
    mkdir -p "$out"

    render "$scheme" templates/xresources.mustache        > "$out/Xresources"
    render "$scheme" templates/kitty.mustache             > "$out/kitty.conf"
    render "$scheme" templates/rofi.mustache              > "$out/rofi.rasi"
    render "$scheme" templates/lazygit.mustache           > "$out/lazygit.yml"
    render "$scheme" templates/emacs-doom-theme.mustache  > "$out/$slug-theme.el"
    render "$scheme" templates/obsidian.mustache          > "$out/obsidian.css"
    render "$scheme" templates/gtk.mustache               > "$out/gtk.css"
    render "$scheme" templates/claude-code.mustache       > "$out/claude-code.json"

    echo "  $slug -> $out/"
done

# Claude Code gets ONE theme slug, burning-sun, whose *contents* the switch
# scripts rewrite. Selecting between two slugs would only move sessions that
# start afterwards — a session already running keeps whichever it resolved at
# launch, which left old sessions on the dark theme against a light terminal.
# Claude Code watches this folder and re-reads a theme when its file changes,
# so swapping contents in place restyles live sessions too.
mkdir -p "$HOME/.claude/themes"
cp "out/dark/claude-code.json" "$HOME/.claude/themes/burning-sun.json"
echo "  claude code -> ~/.claude/themes/burning-sun.json"

# The dark desktop wants the eclipse pulled back so it sits behind the windows
# rather than competing with them; paper uses it at full strength. Regenerated
# only when the source is newer, and falls back to the original if ImageMagick
# is missing, so the switch scripts always have a file to point at.
SRC="wallpaper/solar-eclipse.jpg"
DIM="wallpaper/solar-eclipse-dim.jpg"
if command -v magick >/dev/null 2>&1; then
    if [[ ! -f "$DIM" || "$SRC" -nt "$DIM" ]]; then
        magick "$SRC" -modulate 75,100,100 "$DIM"
        echo "  wallpaper -> $DIM (75% brightness)"
    fi
elif [[ ! -f "$DIM" ]]; then
    cp "$SRC" "$DIM"
    echo "  wallpaper -> $DIM (undimmed; ImageMagick not found)"
fi

# Obsidian takes one theme containing both variants, scoped by .theme-dark /
# .theme-light, and switches between them with its own appearance setting.
OBSIDIAN_VAULT="$HOME/Dropbox/Obsidian/Org/.obsidian"
if [[ -d "$OBSIDIAN_VAULT" ]]; then
    dest="$OBSIDIAN_VAULT/themes/Burning Sun"
    mkdir -p "$dest"
    cat > "$dest/manifest.json" <<'MANIFEST'
{
    "name": "Burning Sun",
    "version": "1.0.0",
    "minAppVersion": "1.0.0",
    "author": "Taylor Lunt",
    "authorUrl": "https://taylor.gl"
}
MANIFEST
    cat out/dark/obsidian.css out/paper/obsidian.css > "$dest/theme.css"
    echo "  obsidian -> $dest/"
fi

# Emacs loads themes from a directory on custom-theme-load-path, so they get a
# copy under its own config rather than being read out of out/ directly.
mkdir -p ../emacs/themes
for scheme in schemes/*.yaml; do
    slug=$(basename "$scheme" .yaml)
    variant=${slug##*-}
    cp "out/$variant/$slug-theme.el"    "../emacs/themes/$slug-theme.el"
done

# lazygit has no include mechanism, so its theme has to be spliced into
# config.yml between markers rather than pointed at.
python3 - <<'SPLICE'
import pathlib, re
cfg = pathlib.Path("../lazygit/config.yml")
theme = pathlib.Path("out/dark/lazygit.yml").read_text()
# keep only the `theme:` mapping, re-indented under the existing `gui:` key
body = theme.split("gui:\n", 1)[1]
block = ("  # BEGIN burning-sun (generated by theme/build.sh)\n"
         + body.rstrip() + "\n"
         + "  # END burning-sun\n")
text = cfg.read_text()
marked = re.compile(r"  # BEGIN burning-sun.*?  # END burning-sun\n", re.S)
if marked.search(text):
    text = marked.sub(block, text)
else:
    text = re.sub(r"^gui:\n", "gui:\n" + block, text, count=1, flags=re.M)
cfg.write_text(text)
SPLICE
echo "  lazygit config.yml spliced"

echo "built $(ls schemes/*.yaml | wc -l) schemes"
