#!/usr/bin/env bash
#
# Apply Burning Sun (dark). Run from cron at 22:00; see switch-to-light-theme.sh.
# Everything it copies is generated by dotfiles/theme/build.sh.

set -euo pipefail

DOTFILES="$HOME/Dropbox/dotfiles"
THEME="$DOTFILES/theme/out/dark"

source "$HOME/.scripts/burning-sun-state.sh"
bs_set_variant "dark"

# The display was hardcoded to :1 here for years while the session actually
# ran on :0, so the cron-driven switch silently did nothing. Detect it.
if [[ -z "${DISPLAY:-}" ]]; then
    for sock in /tmp/.X11-unix/X*; do
        export DISPLAY=":${sock##*/X}"
        break
    done
fi
: "${DISPLAY:?no X display found}"

# Reuse the session bus if we are already inside it; only spawn one when run
# from cron, where there is none.
if [[ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]]; then
    export $(dbus-launch)
fi

# Gnome/GTK
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
# Only the monospace slot is unified; GTK's proportional faces stay as they
# were, because Iosevka's proportional cuts read as mono-ish in body text.
gsettings set org.gnome.desktop.interface monospace-font-name "Iosevka Nerd Font Mono 11"
# GTK — Electron apps (Obsidian) read gtk-3.0/settings.ini, and that file wins
# over gsettings. Leaving it on light Adwaita is what painted a #f6f5f4 frame
# around Obsidian's window on a black desktop.
GTKINI="$HOME/.config/gtk-3.0/settings.ini"
if [[ -f "$GTKINI" ]]; then
    sed -i -e 's/^gtk-theme-name=.*/gtk-theme-name=Adwaita-dark/' \
           -e '/^gtk-application-prefer-dark-theme=/d' "$GTKINI"
    sed -i '/^\[Settings\]/a gtk-application-prefer-dark-theme=1' "$GTKINI"
fi


# GTK colours, generated from the scheme. --remove-destination because these
# paths used to be symlinks into the dotfiles tree; copying through a symlink
# would write back into the repo instead of into the config.
for d in gtk-3.0 gtk-4.0; do
    mkdir -p "$HOME/.config/$d"
    cp -f --remove-destination "$THEME/gtk.css" "$HOME/.config/$d/gtk.css"
done

# i3 (reads the colours out of ~/.Xresources)
cp "$THEME/Xresources" "$HOME/.Xresources"
xrdb -merge "$HOME/.Xresources"
i3-msg reload

# rofi
sed -i 's|^@theme .*|@theme "'"$DOTFILES"'/theme/out/dark/rofi.rasi"|' "$DOTFILES/rofi/config.rasi"

# kitty — kitty.conf `include`s current-theme.conf, and kitty reloads its
# whole config on SIGUSR1, so this recolours every running instance without
# needing remote control or a socket (whose name gets a -PID suffix anyway).
cp "$THEME/kitty.conf" "$DOTFILES/kitty/current-theme.conf"
pkill -x -USR1 kitty 2>/dev/null || true


# obsidian — one theme holds both variants; this flips which one it shows.
# ("obsidian" is Obsidian's name for dark, "moonstone" for light.)
OBSIDIAN="$HOME/Dropbox/Obsidian/Org/.obsidian/appearance.json"
if [[ -f "$OBSIDIAN" ]]; then
    python3 - "$OBSIDIAN" <<'PY'
import json, sys
p = sys.argv[1]
with open(p) as f:
    d = json.load(f)
d["theme"] = "obsidian"
d["cssTheme"] = "Burning Sun"
with open(p, "w") as f:
    json.dump(d, f, indent=2)
    f.write("\n")
PY
fi

# emacs — the running daemon follows the state file written above. Without
# this the button changed every application except emacs, which was only ever
# restyling itself on its own internal timer.
if command -v emacsclient >/dev/null 2>&1; then
    emacsclient --eval '(taylor-gl/auto-update-theme)' >/dev/null 2>&1 || true
fi

# claude code — one theme file whose contents we swap, rather than two files
# selected by name. Claude Code watches this folder and re-reads the theme when
# the file changes, so a session that is already open restyles too; switching
# the *selection* only affects sessions started afterwards.
if [[ -d "$HOME/.claude/themes" ]]; then
    cp -f "$DOTFILES/theme/out/dark/claude-code.json" \
          "$HOME/.claude/themes/burning-sun.json"
fi

# The selection lives in ~/.claude/settings.json, which OUTRANKS ~/.claude.json.
# Both are written so the two cannot disagree — a stale value in settings.json
# silently wins and, if it names a slug that no longer exists, Claude Code drops
# back to its default palette.
for cfg in "$HOME/.claude/settings.json" "$HOME/.claude.json"; do
    [[ -f "$cfg" ]] || continue
    python3 - "$cfg" "custom:burning-sun" <<'PY' || true
import json, os, sys, tempfile
path, theme = sys.argv[1], sys.argv[2]
try:
    with open(path) as f:
        cfg = json.load(f)
except (OSError, ValueError):
    raise SystemExit(0)
if cfg.get("theme") == theme:
    raise SystemExit(0)
cfg["theme"] = theme
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix=".cfg.")
try:
    with os.fdopen(fd, "w") as f:
        json.dump(cfg, f, indent=2)
    os.replace(tmp, path)
except BaseException:
    os.unlink(tmp)
    raise
PY
done

# wallpaper — dark uses the eclipse pulled back to 75% so it sits behind
# the windows instead of competing with them.
feh --bg-fill "$DOTFILES/theme/wallpaper/solar-eclipse-dim.jpg"

# Refresh the theme button in the bar (harmless if i3blocks is not running).
pkill -RTMIN+"$BS_BLOCK_SIGNAL" i3blocks 2>/dev/null || true
