;;; burning-sun-dark-theme.el --- Burning Sun Dark -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; GENERATED by theme/build.sh from theme/schemes/burning-sun-dark.yaml
;; Do not edit — edit the scheme or theme/templates/emacs-doom-theme.mustache.
;;
;; Author: Taylor Lunt (https://taylor.gl)
;;
;;; Commentary:
;;
;; Monochrome and rubrication.
;;
;; Code is set in one ink on one ground. Structure is carried by grey value,
;; italic and weight — not by hue. Vermilion is the rubric: it is spent on
;; types, headings, errors and the things that must be found by eye, and on
;; nothing else. Rainbow delimiters are the one deliberate exception, kept
;; because nesting depth is genuinely easier to read in hue, but desaturated
;; so they do not shout over the text.
;;
;;; Code:

(require 'doom-themes)

(defgroup burning-sun-dark-theme nil
  "Options for the `burning-sun-dark' theme."
  :group 'doom-themes)

(defcustom burning-sun-dark-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a 4px padding to the mode-line.
Can be an integer to determine the exact padding."
  :group 'burning-sun-dark-theme
  :type '(choice integer boolean))

(def-doom-theme burning-sun-dark
  "Burning Sun Dark — monochrome and rubrication."

  ;; name       default            256                16
  ((bg         '("#0a0a0a" "#0a0a0a" "black"     ))
   (fg         '("#ede8e0" "#ede8e0" "brightwhite"     ))
   (bg-alt     '("#141312" "#141312" "brightblack" ))
   (fg-alt     '("#8a8479" "#8a8479" "white" ))

   ;; Nine evenly-spaced steps interpolated along the scheme's own greys.
   ;; base16 only defines seven, and repeating two of them to fill doom's
   ;; ramp is visible when grey value is carrying all the structure.
   (base0      '("#0a0a0a" "#0a0a0a" "black"     ))
   (base1      '("#121110" "#121110" "brightblack" ))
   (base2      '("#1e1e1e" "#1e1e1e" "brightblack" ))
   (base3      '("#3b3835" "#3b3835" "white" ))
   (base4      '("#5f5a52" "#5f5a52" "white" ))
   (base5      '("#817b71" "#817b71" "white" ))
   (base6      '("#c4bfb6" "#c4bfb6" "white" ))
   (base7      '("#efebe4" "#efebe4" "brightwhite"     ))
   (base8      '("#f6f3ee" "#f6f3ee" "brightwhite"     ))

   ;; The rubric, and its two quieter degrees.
   (ember      '("#ff4a00" "#ff4a00" "brightred"       ))
   (ember-dim  '("#e8724a" "#e8724a" "red"             ))
   (ember-deep '("#d0553a" "#d0553a" "red"             ))

   ;; doom-themes and a good deal of third-party face code expect these names
   ;; to exist. Under rubrication they nearly all resolve to the grey ramp;
   ;; only `red' and `orange' stay hot, because they mean "look here".
   (grey       base5)
   (red        ember)
   (orange     ember-dim)
   (yellow     ember-deep)
   (green      '("#a8a196" "#a8a196" "white" ))
   (teal       '("#8a8479" "#8a8479" "white" ))
   (blue       '("#8a8479" "#8a8479" "white" ))
   (dark-blue  '("#5f5a52" "#5f5a52" "white" ))
   (magenta    '("#a8a196" "#a8a196" "white" ))
   (violet     '("#a8a196" "#a8a196" "white" ))
   (cyan       '("#a8a196" "#a8a196" "white" ))
   (dark-cyan  '("#5f5a52" "#5f5a52" "white" ))

   ;; Face categories
   (highlight      ember)
   (vertical-bar   base2)
   (selection      base2)
   (builtin        fg)
   (comments       base4)
   (doc-comments   base6)
   (constants      ember-dim)
   (functions      fg)
   (keywords       base6)
   (methods        fg)
   (operators      base6)
   (type           ember)
   (strings        green)
   (variables      fg)
   (numbers        ember-dim)
   (region         base2)
   (error          ember)
   (warning        ember-deep)
   (success        green)
   (vc-modified    base5)
   (vc-added       green)
   (vc-deleted     ember-dim)

   (modeline-fg     fg)
   (modeline-fg-alt base6)
   (modeline-bg     base1)
   (modeline-bg-alt base1)
   (modeline-bg-inactive     bg)
   (modeline-bg-inactive-alt bg)

   ;; Diff block tints. Deletions carry an ember cast, additions a neutral
   ;; lift, changes sit between — the -hl pair is the same idea one step
   ;; stronger, for the line under point and for word-level refinement.
   ;; Derived from the scheme so the paper variant tints the other way.
   (diff-del-bg '("#271209" "#271209" "brightblack"))
   (diff-del-hl '("#4f1c07" "#4f1c07" "brightblack"))
   (diff-add-bg '("#1a1a19" "#1a1a19" "brightblack"))
   (diff-add-hl '("#2e2e2c" "#2e2e2c" "brightblack"))
   (diff-mod-bg '("#1e1310" "#1e1310" "brightblack"))
   (diff-mod-hl '("#361f17" "#361f17" "brightblack"))

   (-modeline-pad
    (when burning-sun-dark-padded-modeline
      (if (integerp burning-sun-dark-padded-modeline) burning-sun-dark-padded-modeline 4))))

  ;;;; Base theme face overrides
  (((font-lock-comment-face &override) :slant 'italic)
   ((font-lock-keyword-face &override) :slant 'italic)
   ((font-lock-type-face &override) :weight 'medium)
   ((font-lock-constant-face &override) :slant 'italic)
   ((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground ember :weight 'bold)
   (cursor :background ember)
   ((region &override) :background selection :distant-foreground nil)
   ((secondary-selection &override) :background base2)
   ((fringe &override) :background bg)
   ((hl-line &override) :background base1)
   ((vertical-border &override) :background base2 :foreground base2)

   ;;;; The rule beneath a heading, echoing the site's ember hairline
   ((show-paren-match &override) :foreground ember :weight 'bold)

   ;;;; doom-modeline / mood-line
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (when -modeline-pad (list :line-width -modeline-pad :color modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (when -modeline-pad (list :line-width -modeline-pad :color modeline-bg-inactive)))
   (doom-modeline-bar :background ember)
   (doom-modeline-project-dir :foreground ember :weight 'bold)
   (doom-modeline-buffer-modified :foreground ember :weight 'bold)
   (doom-modeline-buffer-file :foreground fg :weight 'bold)

   ;;;; Rainbow delimiters — the one place hue is allowed, for nesting clarity
   (rainbow-delimiters-depth-1-face :foreground "#ff4a00")
   (rainbow-delimiters-depth-2-face :foreground "#c9b896")
   (rainbow-delimiters-depth-3-face :foreground "#7f9e97")
   (rainbow-delimiters-depth-4-face :foreground "#a08fa8")
   (rainbow-delimiters-depth-5-face :foreground "#d0c4b4")
   (rainbow-delimiters-depth-6-face :foreground "#7b8a99")
   (rainbow-delimiters-depth-7-face :foreground "#ff4a00")
   (rainbow-delimiters-depth-8-face :foreground "#c9b896")
   (rainbow-delimiters-depth-9-face :foreground "#7f9e97")
   (rainbow-delimiters-unmatched-face :foreground ember :weight 'bold)
   (rainbow-delimiters-mismatched-face :foreground ember :weight 'bold :underline t)

   ;;;; The rubricated manuscript: org-mode
   ;;   Headings are the illuminated initials — ember, in the proportional
   ;;   companion face. Depth reads as size, not as a different colour.
   (org-document-title :foreground ember :weight 'bold :height 1.5 :family "Iosevka Etoile")
   (org-document-info  :foreground base6 :family "Iosevka Etoile")
   (org-level-1 :foreground ember :weight 'bold   :height 1.3 :family "Iosevka Etoile")
   (org-level-2 :foreground fg    :weight 'bold   :height 1.15 :family "Iosevka Etoile")
   (org-level-3 :foreground fg    :weight 'medium :height 1.05 :family "Iosevka Etoile")
   (org-level-4 :foreground base6 :weight 'medium :family "Iosevka Etoile")
   (org-level-5 :foreground base6 :family "Iosevka Etoile")
   (org-level-6 :foreground base5 :family "Iosevka Etoile")
   (org-todo :foreground ember :weight 'bold)
   (org-done :foreground base5 :weight 'normal :strike-through nil)
   (org-headline-done :foreground base5)
   (org-quote :foreground base6 :slant 'italic)
   (org-verbatim :foreground ember-dim)
   (org-code :foreground fg)
   (org-block :background base1 :foreground fg)
   (org-block-begin-line :background bg :foreground base4 :slant 'italic)
   (org-ellipsis :foreground ember :weight 'bold)
   (org-table :foreground base6)
   (org-link :foreground fg :underline t)
   (org-tag :foreground base5 :weight 'normal)
   (org-date :foreground base5)
   (org-checkbox :foreground ember)
   (org-drawer :foreground base4)
   (org-special-keyword :foreground base4)

   ;;;; markdown, same logic
   (markdown-header-face-1 :foreground ember :weight 'bold :height 1.3 :family "Iosevka Etoile")
   (markdown-header-face-2 :foreground fg    :weight 'bold :height 1.15 :family "Iosevka Etoile")
   (markdown-header-face-3 :foreground fg    :weight 'medium :family "Iosevka Etoile")
   (markdown-header-face-4 :foreground base6 :weight 'medium :family "Iosevka Etoile")
   (markdown-header-delimiter-face :foreground base4)
   (markdown-markup-face :foreground base4)
   (markdown-list-face :foreground ember)
   (markdown-code-face :background base1 :foreground fg)
   (markdown-inline-code-face :background base1 :foreground ember-dim)
   (markdown-url-face :foreground base5)
   (markdown-link-face :foreground fg :underline t)
   (markdown-blockquote-face :foreground base6 :slant 'italic)

   ;;;; Search and match — must be findable at a glance, so: rubric
   ((isearch &override) :background ember :foreground bg :weight 'bold)
   ;; Defined outright, not &override: doom's base lazy-highlight is built
   ;; from &dark/&light blocks and the macro refuses to extend those.
   (lazy-highlight :background base2 :foreground fg
                   :distant-foreground base0 :weight 'bold)
   ((match &override) :background base2 :foreground ember :weight 'bold)
   (isearch-fail :background bg :foreground ember :weight 'bold)
   ((ivy-current-match &override) :background base2 :foreground ember :weight 'bold)
   ((ivy-minibuffer-match-face-1 &override) :foreground ember)
   ((ivy-minibuffer-match-face-2 &override) :foreground ember :weight 'bold)
   ((ivy-minibuffer-match-face-3 &override) :foreground ember :weight 'bold)
   ((ivy-minibuffer-match-face-4 &override) :foreground ember :weight 'bold)
   ((swiper-line-face &override) :background base2)

   ;;;; ---------------------------------------------------------------
   ;;;; Where colour is information
   ;;;;
   ;;;; Everything above this line is rubricated. Everything below it is a
   ;;;; place where removing hue would destroy meaning rather than noise, so
   ;;;; a distinction survives — but drawn with the scheme's own values, not
   ;;;; with imported colour.
   ;;;; ---------------------------------------------------------------

   ;;;; Diffs. Same logic as the terminal: a deletion burns, an addition is
   ;;;; simply more ink. Backgrounds carry the block, foregrounds the line.
   ((diff-added &override)             :background diff-add-bg :foreground fg)
   ((diff-removed &override)           :background diff-del-bg :foreground ember)
   ((diff-changed &override)           :background diff-mod-bg :foreground ember-dim)
   ((diff-indicator-added &override)   :foreground fg          :weight 'bold)
   ((diff-indicator-removed &override) :foreground ember       :weight 'bold)
   ((diff-refine-added &override)      :background diff-add-hl :foreground base8 :weight 'bold)
   ((diff-refine-removed &override)    :background diff-del-hl :foreground ember :weight 'bold)
   ((diff-refine-changed &override)    :background diff-mod-hl :weight 'bold)
   ((diff-header &override)            :foreground base6)
   ((diff-file-header &override)       :foreground fg :weight 'bold)
   ((diff-hunk-header &override)       :foreground ember :slant 'italic)

   ;;;; magit
   (magit-diff-added                     :background diff-add-bg :foreground base7)
   (magit-diff-added-highlight           :background diff-add-hl :foreground fg :weight 'bold)
   (magit-diff-removed                   :background diff-del-bg :foreground ember-dim)
   (magit-diff-removed-highlight         :background diff-del-hl :foreground ember :weight 'bold)
   (magit-diff-base                      :background diff-mod-bg :foreground base6)
   (magit-diff-base-highlight            :background diff-mod-hl :foreground fg)
   (magit-diff-context                   :foreground base5)
   (magit-diff-context-highlight         :background base1 :foreground base6)
   (magit-diff-hunk-heading              :background base1 :foreground base6)
   (magit-diff-hunk-heading-highlight    :background base2 :foreground ember :weight 'bold)
   (magit-diff-lines-heading             :background ember :foreground bg :weight 'bold)
   (magit-diff-file-heading              :foreground fg :weight 'bold)
   (magit-diff-file-heading-highlight    :background base2 :foreground fg :weight 'bold)
   (magit-diffstat-added                 :foreground fg)
   (magit-diffstat-removed               :foreground ember)
   (magit-section-heading                :foreground ember :weight 'bold)
   (magit-section-highlight              :background base1)
   (magit-branch-current                 :foreground ember :weight 'bold :box '(:line-width 1))
   (magit-branch-local                   :foreground fg)
   (magit-branch-remote                  :foreground base6 :slant 'italic)
   (magit-tag                            :foreground ember-dim)
   (magit-hash                           :foreground base5)
   (magit-log-author                     :foreground base6)
   (magit-log-date                       :foreground base5)
   (magit-cherry-equivalent              :foreground base5)
   (magit-cherry-unmatched               :foreground ember)
   (magit-bisect-good                    :foreground fg)
   (magit-bisect-bad                     :foreground ember)
   (magit-bisect-skip                    :foreground base5)
   (magit-signature-good                 :foreground fg)
   (magit-signature-bad                  :foreground ember :weight 'bold)
   (magit-signature-untrusted            :foreground ember-dim)
   (magit-reflog-commit                  :foreground fg)
   (magit-reflog-reset                   :foreground ember)
   (magit-reflog-checkout                :foreground base6)
   (magit-reflog-merge                   :foreground fg)
   (magit-reflog-rebase                  :foreground ember-dim)
   (magit-reflog-cherry-pick             :foreground ember-dim)
   (magit-reflog-remote                  :foreground base6)
   (magit-reflog-other                   :foreground base5)
   (magit-blame-heading                  :background base1 :foreground base6)
   (magit-blame-highlight                :background base2 :foreground fg)

   ;;;; magit-todos inherits the hl-todo ramp set in init.el.

   ;;;; diff-hl fringe: the margin is too narrow for text, so these are the
   ;;;; one place a solid block of colour has to do the whole job.
   (diff-hl-insert         :background fg     :foreground fg)
   (diff-hl-delete         :background ember  :foreground ember)
   (diff-hl-change         :background base6  :foreground base6)
   (diff-hl-dired-insert   :foreground fg)
   (diff-hl-dired-delete   :foreground ember)
   (diff-hl-dired-change   :foreground base6)

   ;;;; Three-way merges are the real exception. Ink-versus-ember has only two
   ;;;; states and a conflict has three, so these separate by background value
   ;;;; as well — mine is lit, theirs is ember, the ancestor recedes.
   (smerge-upper           :background diff-del-bg)
   (smerge-lower           :background diff-add-bg)
   (smerge-base            :background diff-mod-bg)
   (smerge-markers         :background base2 :foreground base6 :weight 'bold)
   (smerge-refined-added   :background diff-add-hl :foreground base8 :weight 'bold)
   (smerge-refined-removed :background diff-del-hl :foreground ember :weight 'bold)

   (ediff-current-diff-A        :background diff-del-bg :foreground ember)
   (ediff-current-diff-B        :background diff-add-bg :foreground fg)
   (ediff-current-diff-C        :background diff-mod-bg :foreground ember-dim)
   (ediff-current-diff-Ancestor :background base1       :foreground base5)
   (ediff-fine-diff-A           :background diff-del-hl :foreground ember :weight 'bold)
   (ediff-fine-diff-B           :background diff-add-hl :foreground base8 :weight 'bold)
   (ediff-fine-diff-C           :background diff-mod-hl :weight 'bold)
   (ediff-fine-diff-Ancestor    :background base2       :weight 'bold)
   (ediff-even-diff-A           :background base1)
   (ediff-even-diff-B           :background base1)
   (ediff-even-diff-C           :background base1)
   (ediff-even-diff-Ancestor    :background base1)
   (ediff-odd-diff-A            :background base1)
   (ediff-odd-diff-B            :background base1)
   (ediff-odd-diff-C            :background base1)
   (ediff-odd-diff-Ancestor     :background base1)

   ;;;; ANSI inside emacs (shell, compilation, vterm). These mirror the kitty
   ;;;; palette exactly, so a `git diff` reads the same in either place.
   ;;;; Defining them here also fixes doom-themes issue #674, which the
   ;;;; custom-set-faces block in init.el used to work around.
   (ansi-color-black          :foreground "#262626"   :background "#262626")
   (ansi-color-red            :foreground "#ff4a00"     :background "#ff4a00")
   (ansi-color-green          :foreground "#c4bfb6"   :background "#c4bfb6")
   (ansi-color-yellow         :foreground "#e8724a"  :background "#e8724a")
   (ansi-color-blue           :foreground "#ff4a00"    :background "#ff4a00")
   (ansi-color-magenta        :foreground "#8a8479" :background "#8a8479")
   (ansi-color-cyan           :foreground "#a8a196"    :background "#a8a196")
   (ansi-color-white          :foreground "#a8a196"   :background "#a8a196")
   (ansi-color-bright-black   :foreground "#5f5a52"   :background "#5f5a52")
   (ansi-color-bright-red     :foreground "#ff4a00"     :background "#ff4a00")
   (ansi-color-bright-green   :foreground "#ede8e0"   :background "#ede8e0")
   (ansi-color-bright-yellow  :foreground "#e8724a"  :background "#e8724a")
   (ansi-color-bright-blue    :foreground "#ff4a00"    :background "#ff4a00")
   (ansi-color-bright-magenta :foreground "#a8a196" :background "#a8a196")
   (ansi-color-bright-cyan    :foreground "#c4bfb6"    :background "#c4bfb6")
   (ansi-color-bright-white   :foreground "#ffffff"   :background "#ffffff")

   ;;;; Compilation: severity is a ramp from ember down into the greys.
   (compilation-error        :foreground ember :weight 'bold)
   (compilation-warning      :foreground ember-deep :slant 'italic)
   (compilation-info         :foreground base6)
   (compilation-line-number  :foreground base5)
   (compilation-column-number :foreground base5)
   (compilation-mode-line-fail :foreground ember :weight 'bold)
   (compilation-mode-line-run  :foreground ember-dim)
   (compilation-mode-line-exit :foreground fg)

   ;;;; Spelling: a misspelling must be findable but must not shout in prose,
   ;;;; so it is the only wave drawn in the secondary rubric.
   (jinx-misspelled :underline `(:style wave :color ,ember-deep))
   (flyspell-incorrect :underline `(:style wave :color ,ember-deep))
   (flyspell-duplicate :underline `(:style wave :color ,base5))

   ;;;; Trailing whitespace is invisible by definition; it needs the ember.
   ((trailing-whitespace &override) :background diff-del-hl)
   ((whitespace-trailing &override) :background diff-del-hl :foreground ember)
   ((whitespace-tab &override) :foreground base3 :background bg)

   ;;;; Errors are always the rubric
   ((flycheck-error &override)   :underline `(:style wave :color ,ember))
   ((flycheck-warning &override) :underline `(:style wave :color ,ember-deep))
   ((flycheck-info &override)    :underline `(:style wave :color ,base5))
   ((flymake-error &override)    :underline `(:style wave :color ,ember))
   ((flymake-warning &override)  :underline `(:style wave :color ,ember-deep))

   ;;;; Completion popups sit on bg-alt with an ember cursor line
   ((company-tooltip &override) :background base1)
   ((company-tooltip-selection &override) :background base2 :foreground ember)
   ((corfu-current &override) :background base2 :foreground ember)
   ((corfu-default &override) :background base1))

  ;;;; Base theme variable overrides
  ())

(provide-theme 'burning-sun-dark)
;;; burning-sun-dark-theme.el ends here
